<?php
namespace OFFLINE\SiteSearch\Classes\Providers;

use Log;
use Indikator\Content\Models\Blog;
use Illuminate\Database\Eloquent\Collection;
use OFFLINE\SiteSearch\Classes\Result;
use OFFLINE\SiteSearch\Models\Settings;

/**
 * Searches the contents generated by the
 * Indikator.Content plugin
 *
 * @package OFFLINE\SiteSearch\Classes\Providers
 */
class IndikatorContentResultsProvider extends ResultsProvider
{
    /**
     * Runs the search for this provider.
     *
     * @return ResultsProvider
     */
    public function search()
    {
        if ( ! $this->isInstalledAndEnabled()) {
            return $this;
        }

        foreach ($this->posts() as $post) {
            // Make this result more relevant, if the query is found in the title
            $relevance = mb_stripos($post->title, $this->query) === false ? 1 : 2;

            $result        = new Result($this->query, $relevance);
            $result->setTitle($post->title);
            $result->setText($post->summary);
            $result->setUrl($this->getUrl($post));
            $result->setMeta($post->published_at);
            $result->setModel($post);
#            Log::info('DEBUG', ['post' => '/storage/app/media' . $post->image]);
#            $result->thumb = '/storage/app/media' . $post->image;
            $result->setThumb($post->image);

            $this->addResult($result);
        }

        return $this;
    }

    /**
     * Get all posts with matching title or content.
     *
     * @return Collection
     */
    protected function posts()
    {
        return Blog::isPublished()
                    ->where(function ($query) {
                        $query->where('title', 'like', "%{$this->query}%")
                            ->orWhere('summary', 'like', "%{$this->query}%")
                            ->orWhere('content', 'like', "%{$this->query}%");
                    })
                   ->orderBy('updated_at', 'desc')
                   ->get();
    }

    /**
     * Checks if the Indikator.Content Plugin is installed and
     * enabled in the config.
     *
     * @return bool
     */
    protected function isInstalledAndEnabled()
    {
        return $this->isPluginAvailable($this->identifier)
        && Settings::get('indikator_news_enabled', true);
    }

    /**
     * Generates the url to a blog post.
     *
     * @param $post
     *
     * @return string
     */
    protected function getUrl($post)
    {
#        $url = trim(Settings::get('indikator_news_posturl', '/news/post'), '/');
#        return $this->withLocalePrefix(implode('/', [$url, $post->slug]));

        // $url = trim(Settings::get('indikator_news_posturl', '/news/post'), '/');
        $langPrefix = $this->translator ? $this->translator->getLocale() : '';

        // fido: Kategorien des Blogs lesen und die erste fuer den Pfad verwenden
        $categories  = $post->getCategories();

#Log::info('DEBUG', ['categories' => $categories]);
#Log::info('DEBUG', ['postslug'       => $post->slug]);
#Log::info('DEBUG', ['array_key_first'     => array_key_first($categories)]);

        if (array_key_first($categories)) {
            $url = implode('/', [$langPrefix, $categories[array_key_first($categories)]['slug'], $post->slug]);
        } else {
            $url = '/';
        }

        return $url;
    }

    /**
     * Display name for this provider.
     *
     * @return mixed
     */
    public function displayName()
    {
        return Settings::get('indikator_news_label', 'Content');
    }

    /**
     * Returns the plugin's identifier string.
     *
     * @return string
     */
    public function identifier()
    {
        return 'Indikator.Content';
    }
}
