<?php
namespace OFFLINE\SiteSearch\Classes\Providers;

use Illuminate\Database\Eloquent\Collection;
use Meloncart\Shop\Models\Product;
use OFFLINE\SiteSearch\Classes\Result;
use OFFLINE\SiteSearch\Models\Settings;

/**
 * Searches the products generated by the
 * Meloncart.Shop plugin
 *
 * @package OFFLINE\SiteSearch\Classes\Providers
 */
class MeloncartProductsResultsProvider extends ResultsProvider
{
    /**
     * Runs the search for this provider.
     *
     * @return ResultsProvider
     */
    public function search()
    {
        if ( ! $this->isInstalledAndEnabled()) {
            return $this;
        }

        foreach ($this->products() as $product) {
            // Make this result more relevant, if the query is found in the name
            $relevance = mb_stripos($product->name, $this->query) === false ? 1 : 2;

            $result = new Result($this->query, $relevance);
            $result->setTitle($product->title ?: $product->name);
            $result->setText($product->short_description ?: $product->description);
            $result->setUrl($product->pageUrl());
            $result->setThumb($this->getThumb($product->images));
            $result->setModel($product);

            $this->addResult($result);
        }

        return $this;
    }

    /**
     * Get all visible products with matching name/title/short_description,
     * using the plugin's own front-end visibility scope and searchable
     * column list so results stay consistent with the storefront.
     *
     * @return Collection
     */
    protected function products()
    {
        return Product::applyVisible()
            ->with('images')
            ->searchWhere($this->query, Product::$searchableColumns)
            ->orderBy('updated_at', 'desc')
            ->get();
    }

    /**
     * Checks if the Meloncart.Shop Plugin is installed and
     * enabled in the config.
     *
     * @return bool
     */
    protected function isInstalledAndEnabled()
    {
        return $this->isPluginAvailable($this->identifier)
            && Settings::get('meloncart_products_enabled', true);
    }

    /**
     * Display name for this provider.
     *
     * @return mixed
     */
    public function displayName()
    {
        return Settings::get('meloncart_products_label', 'Product');
    }

    /**
     * Returns the plugin's identifier string.
     *
     * @return string
     */
    public function identifier()
    {
        return 'Meloncart.Shop';
    }
}
