<?php
namespace OFFLINE\SiteSearch\Classes\Providers;

use Cms;
use Illuminate\Database\Eloquent\Collection;
use Meloncart\Shop\Models\Manufacturer;
use OFFLINE\SiteSearch\Classes\Result;
use OFFLINE\SiteSearch\Models\Settings;

/**
 * Searches the manufacturers generated by the
 * Meloncart.Shop plugin
 *
 * @package OFFLINE\SiteSearch\Classes\Providers
 */
class MeloncartManufacturersResultsProvider extends ResultsProvider
{
    /**
     * Runs the search for this provider.
     *
     * @return ResultsProvider
     */
    public function search()
    {
        if ( ! $this->isInstalledAndEnabled()) {
            return $this;
        }

        foreach ($this->manufacturers() as $manufacturer) {
            $relevance = mb_stripos($manufacturer->name, $this->query) === false ? 1 : 2;

            $result = new Result($this->query, $relevance);
            $result->setTitle($manufacturer->name);
            $result->setText($manufacturer->description);
            $result->setUrl($this->getUrl($manufacturer));
            $result->setModel($manufacturer);

            $this->addResult($result);
        }

        return $this;
    }

    /**
     * Get all visible manufacturers with a matching name/description.
     *
     * @return Collection
     */
    protected function manufacturers()
    {
        return Manufacturer::where('is_hidden', '<>', true)
            ->searchWhere($this->query, ['name', 'description'])
            ->get();
    }

    /**
     * Manufacturer has no pageUrl() of its own — resolve it via the same
     * "catalog" entry-point mechanism Product/Category rely on. Returns ''
     * (safely dropped by Result::setUrl()) until the active theme declares
     * a page with `[catalog] lookup = "manufacturer"`.
     */
    protected function getUrl(Manufacturer $manufacturer): string
    {
        return Cms::entryUrl('catalog', [
            'id' => $manufacturer->id,
            'baseid' => $manufacturer->baseid,
            'slug' => $manufacturer->slug,
        ], ['lookup' => 'manufacturer']) ?: '';
    }

    /**
     * Checks if the Meloncart.Shop Plugin is installed and
     * enabled in the config.
     *
     * @return bool
     */
    protected function isInstalledAndEnabled()
    {
        return $this->isPluginAvailable($this->identifier)
            && Settings::get('meloncart_manufacturers_enabled', true);
    }

    /**
     * Display name for this provider.
     *
     * @return mixed
     */
    public function displayName()
    {
        return Settings::get('meloncart_manufacturers_label', 'Manufacturer');
    }

    /**
     * Returns the plugin's identifier string.
     *
     * @return string
     */
    public function identifier()
    {
        return 'Meloncart.Shop';
    }
}
