<?php
namespace OFFLINE\SiteSearch\Classes\Providers;

use Cms;
use Illuminate\Database\Eloquent\Collection;
use Meloncart\Shop\Models\Category;
use OFFLINE\SiteSearch\Classes\Result;
use OFFLINE\SiteSearch\Models\Settings;

/**
 * Searches the categories generated by the
 * Meloncart.Shop plugin
 *
 * @package OFFLINE\SiteSearch\Classes\Providers
 */
class MeloncartCategoriesResultsProvider extends ResultsProvider
{
    /**
     * Runs the search for this provider.
     *
     * @return ResultsProvider
     */
    public function search()
    {
        if ( ! $this->isInstalledAndEnabled()) {
            return $this;
        }

        foreach ($this->categories() as $category) {
            $relevance = mb_stripos($category->name, $this->query) === false ? 1 : 2;

            $result = new Result($this->query, $relevance);
            $result->setTitle($category->title ?: $category->name);
            $result->setText($category->short_description ?: $category->description);
            $result->setUrl($this->getUrl($category));
            $result->setModel($category);

            $this->addResult($result);
        }

        return $this;
    }

    /**
     * Get all visible categories with a matching name/title/description.
     *
     * @return Collection
     */
    protected function categories()
    {
        return Category::applyVisible()
            ->searchWhere($this->query, ['name', 'title', 'short_description', 'description'])
            ->get();
    }

    /**
     * Category::pageUrl() has no automatic entry-point fallback (unlike
     * Product::pageUrl()), so resolve it the same way Product does
     * internally: via the theme's page declaring `[catalog] lookup =
     * "category"`. Returns '' if no such page exists yet, same as
     * Product::pageUrl() would for an unmapped page.
     */
    protected function getUrl(Category $category): string
    {
        return Cms::entryUrl('catalog', [
            'id' => $category->id,
            'baseid' => $category->baseid,
            'slug' => $category->slug,
            'fullslug' => $category->fullslug,
        ], ['lookup' => 'category']) ?: '';
    }

    /**
     * Checks if the Meloncart.Shop Plugin is installed and
     * enabled in the config.
     *
     * @return bool
     */
    protected function isInstalledAndEnabled()
    {
        return $this->isPluginAvailable($this->identifier)
            && Settings::get('meloncart_categories_enabled', true);
    }

    /**
     * Display name for this provider.
     *
     * @return mixed
     */
    public function displayName()
    {
        return Settings::get('meloncart_categories_label', 'Category');
    }

    /**
     * Returns the plugin's identifier string.
     *
     * @return string
     */
    public function identifier()
    {
        return 'Meloncart.Shop';
    }
}
